name: toff
channels:
  - conda-forge
dependencies:
  # - openmm
  # - openff-toolkit
  # - openmmforcefields
  - ipykernel
  - ipython
  - ipywidgets
  - pip
  - python==3.9.*
  - nbsphinx
  - sphinx==5.3.0
  - conda-build
  - pip:
    - parmed
    - pyyaml
    - sphinx_copybutton
    - myst_nb
    - recommonmark
    - sphinx_book_theme