name: toff
channels:
  - conda-forge
dependencies:
  # - openmm
  # - openff-toolkit
  # - openmmforcefields
  - ipykernel
  - ipython
  - ipywidgets
  - pip
  - python==3.9.*
  - conda-build
  - pip:
    - myst-nb
    - myst-parser
    - sphinx_book_theme
    - sphinx==7.2.6
    - sphinx_design
    - sphinxcontrib-katex
    - sphinx-inline-tabs
    - sphinx_copybutton