name: toff
channels:
  - conda-forge
dependencies:
  - pip
  - python==3.*
  - openmm
  - openff-toolkit
  - nbsphinx
  - sphinx 
  - pip:
    - parmed
    - pyyaml
    - recommonmark
    - sphinx_rtd_theme